# generated by datamodel-codegen:
#   filename:  holiday.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Reason(Enum):
    public_holiday = "PUBLIC_HOLIDAY"
    temporary_closure = "TEMPORARY_CLOSURE"
    special = "SPECIAL"


class Holiday(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    """
    ISO 8601 closure date in Asia/Shanghai, e.g. 2026-01-01
    """
    exchange: Exchange
    """
    Exchange the closure applies to
    """
    reason: Reason
    """
    PUBLIC_HOLIDAY / TEMPORARY_CLOSURE / SPECIAL
    """
    note: str | None = None
    """
    Optional free-text reason, e.g. 元旦 / 台风临时休市
    """
