# generated by datamodel-codegen:
#   filename:  trading-session.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Kind(Enum):
    continuous = "CONTINUOUS"
    open_auction = "OPEN_AUCTION"
    close_auction = "CLOSE_AUCTION"
    break_ = "BREAK"
    night = "NIGHT"


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class TradingSession(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: str = Field(..., alias="sessionId", pattern="^[a-z][a-z0-9-]*$")
    """
    Stable machine id, e.g. open-auction / morning / afternoon
    """
    kind: Kind
    """
    Session kind: CONTINUOUS / OPEN_AUCTION / CLOSE_AUCTION / BREAK / NIGHT
    """
    start: str = Field(..., pattern="^([01]\\d|2[0-3]):[0-5]\\d$")
    """
    Local clock HH:MM (Asia/Shanghai), inclusive start
    """
    end: str = Field(..., pattern="^([01]\\d|2[0-3]):[0-5]\\d$")
    """
    Local clock HH:MM (Asia/Shanghai), exclusive end
    """
    exchange: Exchange
    """
    Exchange this session belongs to
    """
    crosses_midnight: bool | None = Field(False, alias="crossesMidnight")
    """
    True when the session ends after midnight (start > end); it belongs to its start trading day
    """
