# generated by datamodel-codegen:
#   filename:  trading-day.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Reason(Enum):
    weekend = "WEEKEND"
    public_holiday = "PUBLIC_HOLIDAY"
    temporary_closure = "TEMPORARY_CLOSURE"
    special = "SPECIAL"


class TradingDay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    """
    ISO 8601 calendar date in Asia/Shanghai, e.g. 2026-08-13
    """
    exchange: Exchange
    """
    Exchange this day entry applies to
    """
    is_trading_day: bool = Field(..., alias="isTradingDay")
    """
    Whether the exchange trades on this date; weekends and holidays never count as trading days
    """
    reason: Reason | None = None
    """
    Optional reason when isTradingDay is false
    """
    note: str | None = None
    """
    Optional free-text note (e.g. holiday name or closure cause)
    """
