# generated by datamodel-codegen:
#   filename:  raw-content.json

from __future__ import annotations

from enum import Enum, StrEnum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    ValidationError,
    model_validator,
)
from pydantic_core import InitErrorDetails


class ContentType(Enum):
    news = "NEWS"
    announcement = "ANNOUNCEMENT"
    research = "RESEARCH"
    interaction = "INTERACTION"
    social = "SOCIAL"


class FingerprintVersion(StrEnum):
    sha256_v1 = "sha256-v1"


class ContentSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_id: str = Field(..., alias="sourceId", min_length=1)
    """
    Source provider or platform identifier
    """
    source_version: str = Field(..., alias="sourceVersion", min_length=1)
    """
    Provider data/API version
    """
    evidence_id: str = Field(..., alias="evidenceId", min_length=1)
    """
    Immutable identifier of the raw evidence this content derives from
    """


class LicenseMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    license_id: str = Field(..., alias="licenseId", min_length=1)
    """
    License or right-grant identifier
    """
    usage_restriction: str = Field(..., alias="usageRestriction", min_length=1)
    """
    Usage restriction; a non-restricting license states it explicitly
    """
    authorized: StrictBool
    """
    Explicit authorization; usable only when true
    """


class RawContent(BaseModel):
    @model_validator(mode="after")
    def validate_deleted_condition(self) -> RawContent:
        if self.deleted and self.deleted_at is None:
            raise ValidationError.from_exception_data(
                "RawContent",
                [
                    InitErrorDetails(
                        type="value_error",
                        loc=("deletedAt",),
                        input=None,
                        ctx={"error": ValueError("deleted content must have deletedAt")},
                    )
                ],
            )
        if not self.deleted and self.deleted_at is not None:
            raise ValidationError.from_exception_data(
                "RawContent",
                [
                    InitErrorDetails(
                        type="value_error",
                        loc=("deletedAt",),
                        input=self.deleted_at,
                        ctx={"error": ValueError("non-deleted content must not have deletedAt")},
                    )
                ],
            )
        return self

    model_config = ConfigDict(
        extra="forbid",
    )
    content_type: ContentType = Field(..., alias="contentType")
    """
    Content category: NEWS / ANNOUNCEMENT / RESEARCH / INTERACTION / SOCIAL
    """
    record_id: str = Field(..., alias="recordId", min_length=1)
    """
    Stable identifier of the content lineage; shared by every version
    """
    version_id: str = Field(..., alias="versionId", pattern="^[0-9a-f]{64}$")
    """
    Unique identifier of the current immutable version (64-hex SHA-256)
    """
    url: str = Field(..., min_length=1)
    """
    Original URL or source locator for the raw content
    """
    title: str
    """
    Original raw title
    """
    body: str
    """
    Original raw body
    """
    publish_time: AwareDatetime = Field(..., alias="publishTime")
    """
    When the content was published (timezone-aware)
    """
    ingest_time: AwareDatetime = Field(..., alias="ingestTime")
    """
    When Kunlun ingested the content (timezone-aware)
    """
    available_time: AwareDatetime = Field(..., alias="availableTime")
    """
    Earliest time this record may enter research or downstream computation
    """
    fingerprint: str = Field(..., pattern="^[0-9a-f]{64}$")
    """
    Deterministic 64-hex lowercase SHA-256 content fingerprint
    """
    fingerprint_algorithm_version: FingerprintVersion = Field(
        ..., alias="fingerprintAlgorithmVersion"
    )
    """
    Fingerprint algorithm version
    """
    source: ContentSource
    """
    Current source attribution
    """
    license: LicenseMetadata
    """
    License, authorization and usage-restriction metadata
    """
    original_source: ContentSource | None = Field(None, alias="originalSource")
    """
    Original source for a repost; absent for non-repost content
    """
    previous_version_id: str | None = Field(
        None, alias="previousVersionId", pattern="^[0-9a-f]{64}$"
    )
    """
    versionId of the direct predecessor; null for the first version
    """
    deleted: StrictBool
    """
    Whether this content has been deleted; deletion preserves evidence
    """
    deleted_at: AwareDatetime | None = Field(None, alias="deletedAt")
    """
    Deletion time; required when deleted is true, and not before availableTime
    """
