# generated by datamodel-codegen:
#   filename:  raw-content.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ContentType(Enum):
    news = "NEWS"
    announcement = "ANNOUNCEMENT"
    research = "RESEARCH"
    interaction = "INTERACTION"
    social = "SOCIAL"


class ContentSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_id: str = Field(..., alias="sourceId", min_length=1)
    """
    Source provider or platform identifier
    """
    source_version: str = Field(..., alias="sourceVersion", min_length=1)
    """
    Provider data/API version
    """
    evidence_id: str = Field(..., alias="evidenceId", min_length=1)
    """
    Immutable identifier of the raw evidence this content derives from
    """


class LicenseMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    license_id: str = Field(..., alias="licenseId", min_length=1)
    """
    License or right-grant identifier
    """
    usage_restriction: str = Field(..., alias="usageRestriction", min_length=1)
    """
    Usage restriction; a non-restricting license states it explicitly
    """
    authorized: bool
    """
    Whether use of the content is authorized
    """


class RawContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content_type: ContentType = Field(..., alias="contentType")
    """
    Content category: NEWS / ANNOUNCEMENT / RESEARCH / INTERACTION / SOCIAL
    """
    url: str = Field(..., min_length=1)
    """
    Original URL or source locator for the raw content
    """
    title: str
    """
    Original raw title
    """
    body: str
    """
    Original raw body
    """
    publish_time: AwareDatetime = Field(..., alias="publishTime")
    """
    When the content was published (timezone-aware, never later than ingestTime)
    """
    ingest_time: AwareDatetime = Field(..., alias="ingestTime")
    """
    When Kunlun ingested the content (timezone-aware)
    """
    fingerprint: str
    """
    Deterministic content fingerprint (see fingerprintAlgorithmVersion)
    """
    fingerprint_algorithm_version: str = Field(
        ..., alias="fingerprintAlgorithmVersion", min_length=1
    )
    """
    Algorithm version used to compute the fingerprint
    """
    source: ContentSource
    """
    Current source attribution
    """
    license: LicenseMetadata
    """
    License, authorization and usage-restriction metadata
    """
    original_source: ContentSource | None = Field(None, alias="originalSource")
    """
    Original source for a repost; absent for non-repost content
    """
    previous_fingerprint: str | None = Field(None, alias="previousFingerprint")
    """
    Fingerprint of the version this record supersedes; absent for the first version
    """
    deleted: bool
    """
    Whether this content has been deleted; deletion preserves evidence
    """
    deleted_at: AwareDatetime | None = Field(None, alias="deletedAt")
    """
    Deletion time (timezone-aware); required when deleted is true
    """
