# generated by datamodel-codegen:
#   filename:  limit-event.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class EventType(Enum):
    limit_up = "LIMIT_UP"
    limit_down = "LIMIT_DOWN"
    seal = "SEAL"
    break_seal = "BREAK_SEAL"
    open_count = "OPEN_COUNT"


class LimitEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^\\d{6}\\.(SH|SZ|BJ)$")
    """
    Instrument unified code
    """
    exchange: Exchange
    """
    Exchange code
    """
    date: date_aliased
    """
    Trading day in Asia/Shanghai
    """
    event_type: EventType = Field(..., alias="eventType")
    """
    LIMIT_UP / LIMIT_DOWN / SEAL / BREAK_SEAL / OPEN_COUNT
    """
    timestamp: AwareDatetime
    """
    Event time, UTC ISO 8601
    """
    price: float = Field(..., ge=0.0)
    """
    Event price in CNY
    """
    open_count: int | None = Field(None, alias="openCount", ge=0)
    """
    Number of times the seal has been opened
    """
