# generated by datamodel-codegen:
#   filename:  limit-pool-snapshot.json

from __future__ import annotations

from datetime import date as date_aliased

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class LimitPoolSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    """
    Trading day in Asia/Shanghai
    """
    timestamp: AwareDatetime
    """
    Snapshot time, UTC ISO 8601
    """
    limit_up_count: int = Field(..., alias="limitUpCount", ge=0)
    """
    Number of limit-up instruments
    """
    limit_down_count: int = Field(..., alias="limitDownCount", ge=0)
    """
    Number of limit-down instruments
    """
    sealed_count: int = Field(..., alias="sealedCount", ge=0)
    """
    Number of sealed (unopened) limit-up instruments
    """
    limit_up_instruments: list[str] | None = Field(None, alias="limitUpInstruments")
    """
    Limit-up unified codes
    """
    limit_down_instruments: list[str] | None = Field(None, alias="limitDownInstruments")
    """
    Limit-down unified codes
    """
    first_seal_time: AwareDatetime | None = Field(None, alias="firstSealTime")
    """
    Earliest first-seal event time across the pool, UTC ISO 8601, or null when none sealed
    """
    last_seal_time: AwareDatetime | None = Field(None, alias="lastSealTime")
    """
    Latest seal event time across the pool, UTC ISO 8601, or null when none sealed
    """
    total_open_count: int | None = Field(None, alias="totalOpenCount", ge=0)
    """
    Total number of seal openings (break-then-reseal) across the pool
    """
