# generated by datamodel-codegen:
#   filename:  fund-nav.json

from __future__ import annotations

from datetime import date as date_aliased
from decimal import Decimal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator


class FundNav(BaseModel):
    @field_validator("nav", "inav", mode="before")
    @classmethod
    def reject_binary_float(cls, value: object) -> object:
        if isinstance(value, float):
            raise TypeError("float is not an accepted decimal boundary value")
        return value

    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^\\d{6}\\.(SH|SZ|BJ)$")
    """
    Instrument unified code, e.g. 518880.SH
    """
    date: date_aliased
    """
    NAV reference date in Asia/Shanghai
    """
    nav: Decimal = Field(..., ge=Decimal("0"))
    """
    Net asset value reference amount
    """
    inav: Decimal | None = Field(..., ge=Decimal("0"))
    """
    Indicative NAV reference amount, when available
    """
    event_time: AwareDatetime = Field(..., alias="eventTime")
    """
    Economic observation/event time (timezone required)
    """
    publish_time: AwareDatetime = Field(..., alias="publishTime")
    """
    Provider publication time (timezone required)
    """
    ingest_time: AwareDatetime = Field(..., alias="ingestTime")
    """
    Kunlun ingest time (timezone required)
    """
    available_time: AwareDatetime = Field(..., alias="availableTime")
    """
    Earliest research availability time (timezone required)
    """
    processing_time: AwareDatetime = Field(..., alias="processingTime")
    """
    Normalization/processing time (timezone required)
    """
    raw_object_id: str = Field(..., alias="rawObjectId", min_length=1)
    """
    Immutable raw evidence/object identifier
    """
    source: str = Field(..., min_length=1)
    """
    Data source provenance identifier
    """
