# generated by datamodel-codegen:
#   filename:  precious-metal-fund.json

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class FundAssetClass(Enum):
    gold = "GOLD"
    silver = "SILVER"
    other = "OTHER"


class UnderlyingCommodity(Enum):
    gold = "GOLD"
    silver = "SILVER"
    other = "OTHER"


class Currency(Enum):
    cny = "CNY"


class PreciousMetalFund(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^[A-Z]{2}\\.\\d{6}$")
    """
    Instrument unified code, e.g. SH.518880
    """
    exchange: Exchange
    """
    Exchange code
    """
    fund_asset_class: FundAssetClass = Field(..., alias="fundAssetClass")
    """
    Fund asset class: GOLD / SILVER / OTHER
    """
    underlying_commodity: UnderlyingCommodity = Field(..., alias="underlyingCommodity")
    """
    Underlying commodity, explicit (never guessed from name)
    """
    currency: Currency
    """
    Trading currency, must be CNY
    """
    benchmark: str
    """
    Benchmark index or commodity, e.g. Au99.99
    """
    management_fee_rate: float = Field(..., alias="managementFeeRate", ge=0.0)
    """
    Annual management fee rate (0-1)
    """
    valid_from: date = Field(..., alias="validFrom")
    """
    Start of validity in Asia/Shanghai
    """
    valid_to: date | None = Field(None, alias="validTo")
    """
    End of validity, null means currently valid
    """
    source: str
    """
    Data source provenance
    """
