# generated by datamodel-codegen:
#   filename:  health-status-v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class HealthStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    """
    Current health status
    """
    timestamp: AwareDatetime
    """
    ISO 8601 timestamp of the check
    """
    version: str
    """
    Service version string
    """
