# generated by datamodel-codegen:
#   filename:  exchange.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class Code(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Country(Enum):
    cn = "CN"


class Currency(Enum):
    cny = "CNY"


class Exchange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Code
    """
    Exchange code used in the unified instrument code (600000.SH)
    """
    name: str
    """
    Full exchange name in Chinese
    """
    abbreviation: str
    """
    Common Chinese short name
    """
    mic: str
    """
    ISO 10383 Market Identifier Code (XSHG / XSHE / XBES)
    """
    country: Country
    """
    ISO 3166-1 alpha-2 country code
    """
    currency: Currency
    """
    Settlement currency of the exchange
    """
