# generated by datamodel-codegen:
#   filename:  trading-status.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class Value(Enum):
    listed = "LISTED"
    suspended = "SUSPENDED"
    st = "ST"
    delisted = "DELISTED"


class TradingStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: Value
    """
    LISTED: 正常上市; SUSPENDED: 停牌; ST: 风险警示 (ST/*ST); DELISTED: 退市
    """
    label: str
    """
    Human-readable label in Chinese
    """
