# generated by datamodel-codegen:
#   filename:  instrument.json

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Board(Enum):
    main = "MAIN"
    chinext = "CHINEXT"
    star = "STAR"
    bse = "BSE"


class Type(Enum):
    stock = "STOCK"
    etf = "ETF"
    lof = "LOF"
    fund = "FUND"


class TradingStatus(Enum):
    listed = "LISTED"
    suspended = "SUSPENDED"
    st = "ST"
    delisted = "DELISTED"


class Currency(Enum):
    cny = "CNY"


class Instrument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^[A-Z]{2}\\.\\d{6}$")
    """
    Unified domain key in the form {EXCHANGE}.{code}, e.g. SH.600000
    """
    code: str = Field(..., pattern="^\\d{6}$")
    """
    Raw 6-digit exchange code
    """
    exchange: Exchange
    """
    Exchange code; must match the unifiedCode prefix
    """
    board: Board
    """
    Listing board
    """
    type: Type
    """
    Security type: STOCK / ETF / LOF / FUND
    """
    name: str
    """
    Security display name
    """
    trading_status: TradingStatus = Field(..., alias="tradingStatus")
    """
    Trading status; ST and delisting are fields, not code changes
    """
    currency: Currency
    """
    Trading currency
    """
    list_date: date | None = Field(None, alias="listDate")
    """
    Optional first listing date (ISO 8601 date)
    """
    delist_date: date | None = Field(None, alias="delistDate")
    """
    Optional delisting date (ISO 8601 date)
    """
