# generated by datamodel-codegen:
#   filename:  board.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class Id(Enum):
    main = "MAIN"
    chinext = "CHINEXT"
    star = "STAR"
    bse = "BSE"


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Board(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    """
    Board identifier: MAIN (主板), CHINEXT (创业板), STAR (科创板), BSE (北交所)
    """
    name: str
    """
    Board name in Chinese
    """
    exchange: Exchange
    """
    Exchange the board belongs to
    """
