# generated by datamodel-codegen:
#   filename:  adjustment-factor.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class FactorType(Enum):
    forward = "FORWARD"
    backward = "BACKWARD"


class AdjustmentFactor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^[A-Z]{2}\\.\\d{6}$")
    """
    Instrument unified code, e.g. SH.600000
    """
    exchange: Exchange
    """
    Exchange code
    """
    date: date_aliased
    """
    Ex-dividend date in Asia/Shanghai
    """
    factor: float = Field(..., gt=0.0)
    """
    Adjustment factor, must be strictly > 0
    """
    factor_type: FactorType = Field(..., alias="factorType")
    """
    FORWARD / BACKWARD adjustment
    """
    note: str | None = None
    """
    Optional free-text note
    """
