# generated by datamodel-codegen:
#   filename:  tick.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Direction(Enum):
    buy = "BUY"
    sell = "SELL"
    neutral = "NEUTRAL"


class TradeType(Enum):
    match = "MATCH"
    auction = "AUCTION"
    block = "BLOCK"


class Tick(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^[A-Z]{2}\\.\\d{6}$")
    """
    Instrument unified code, e.g. SH.600000
    """
    exchange: Exchange
    """
    Exchange code
    """
    date: date_aliased
    """
    Trading day in Asia/Shanghai, e.g. 2026-08-13
    """
    timestamp: AwareDatetime
    """
    Trade time, UTC ISO 8601 with millisecond precision
    """
    price: float = Field(..., ge=0.0)
    """
    Trade price in CNY
    """
    volume: int = Field(..., ge=0)
    """
    Trade volume in shares
    """
    amount: float = Field(..., ge=0.0)
    """
    Trade turnover in CNY
    """
    direction: Direction
    """
    Aggressor direction: BUY / SELL / NEUTRAL
    """
    trade_type: TradeType = Field(..., alias="tradeType")
    """
    MATCH / AUCTION / BLOCK
    """
