# generated by datamodel-codegen:
#   filename:  corporate-action.json

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class ActionType(Enum):
    dividend = "DIVIDEND"
    stock_dividend = "STOCK_DIVIDEND"
    split = "SPLIT"
    rights_issue = "RIGHTS_ISSUE"


class CorporateAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^[A-Z]{2}\\.\\d{6}$")
    """
    Instrument unified code, e.g. SH.600000
    """
    exchange: Exchange
    """
    Exchange code
    """
    ex_date: date = Field(..., alias="exDate")
    """
    Ex-date in Asia/Shanghai
    """
    action_type: ActionType = Field(..., alias="actionType")
    """
    DIVIDEND / STOCK_DIVIDEND / SPLIT / RIGHTS_ISSUE
    """
    description: str
    """
    Human-readable description
    """
    per_share_cash: float | None = Field(None, alias="perShareCash", ge=0.0)
    """
    Cash dividend per share in CNY (optional)
    """
    per_share_stock: float | None = Field(None, alias="perShareStock", ge=0.0)
    """
    Stock dividend per share (optional)
    """
    ratio: float | None = Field(None, ge=0.0)
    """
    Rights issue ratio (optional)
    """
