# generated by datamodel-codegen:
#   filename:  bar.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Exchange(Enum):
    sh = "SH"
    sz = "SZ"
    bj = "BJ"


class Interval(Enum):
    daily = "DAILY"
    minute_1 = "MINUTE_1"
    minute_5 = "MINUTE_5"


class Session(Enum):
    continuous = "CONTINUOUS"
    open_auction = "OPEN_AUCTION"
    close_auction = "CLOSE_AUCTION"


class PriceType(Enum):
    raw = "RAW"
    forward_adjusted = "FORWARD_ADJUSTED"
    backward_adjusted = "BACKWARD_ADJUSTED"


class Bar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^[A-Z]{2}\\.\\d{6}$")
    """
    Instrument unified code, e.g. SH.600000
    """
    exchange: Exchange
    """
    Exchange code
    """
    date: date_aliased
    """
    Trading day in Asia/Shanghai, e.g. 2026-08-13
    """
    interval: Interval
    """
    Bar interval: DAILY / MINUTE_1 / MINUTE_5
    """
    session: Session
    """
    Session the bar belongs to
    """
    timestamp: AwareDatetime
    """
    Bar start time, UTC ISO 8601 with millisecond precision
    """
    open: float = Field(..., ge=0.0)
    """
    Open price in CNY
    """
    high: float = Field(..., ge=0.0)
    """
    High price in CNY
    """
    low: float = Field(..., ge=0.0)
    """
    Low price in CNY
    """
    close: float = Field(..., ge=0.0)
    """
    Close price in CNY
    """
    volume: int = Field(..., ge=0)
    """
    Volume in shares
    """
    amount: float = Field(..., ge=0.0)
    """
    Turnover in CNY
    """
    price_type: PriceType = Field(..., alias="priceType")
    """
    RAW (trade price) / FORWARD_ADJUSTED / BACKWARD_ADJUSTED (research price)
    """
    suspended: bool | None = False
    """
    True when the instrument was suspended for this bar
    """
