# generated by datamodel-codegen:
#   filename:  sector.json

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Kind(Enum):
    industry = "INDUSTRY"
    concept = "CONCEPT"
    theme = "THEME"


class Sector(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sector_id: str = Field(..., alias="sectorId")
    """
    Stable sector id
    """
    name: str
    """
    Display name
    """
    parent_id: str | None = Field(None, alias="parentId")
    """
    Parent sector id (null for a root)
    """
    kind: Kind
    """
    INDUSTRY / CONCEPT / THEME
    """
    source: str
    """
    Data source provenance
    """
    valid_from: date = Field(..., alias="validFrom")
    """
    Start of validity
    """
    valid_to: date | None = Field(None, alias="validTo")
    """
    End of validity, null means current
    """
    aliases: list[str]
    """
    Alternative names
    """
