# generated by datamodel-codegen:
#   filename:  sector-membership.json

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, ConfigDict, Field


class SectorMembership(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unified_code: str = Field(..., alias="unifiedCode", pattern="^\\d{6}\\.(SH|SZ|BJ)$")
    """
    Instrument unified code
    """
    sector_id: str = Field(..., alias="sectorId")
    """
    Sector id
    """
    valid_from: date = Field(..., alias="validFrom")
    """
    Start of membership validity
    """
    valid_to: date | None = Field(None, alias="validTo")
    """
    End of membership validity, null means current
    """
    source: str
    """
    Data source provenance
    """
